### ISSUE TITLE
Unknown blueprint: resource

### ISSUE THREAD

**Issue by alvinkatojr** [frank06/bookstore-client#1]
With the update to ember-cli v3.1 running: ```ember generate resource books title:string price:number author:belongs_to publisher:belongs_to``` results in a ```Unknown blueprint: resource``` error. 

The solution it seems is creating a resource blueprint but the documentation is not clear. Do you have a solution that can help people following your tutorial while running the latest version of ember-cli?

**Comment by frank06** [comment]
Hey @alvinkatojr I'm sorry - i wrote an updated version of the article that I need to publish. Fro now use `model` instead of `resource`

**Comment by alvinkatojr** [comment]
Hi @frank06 thanks for the fast response. Wonderful I guess I'll do that then. It was fun reading about blueprints but it was taking too much time. 
When do you intend to publish the updated version of the article?

**Comment by frank06** [comment]
I really want to push it very soon but there are a few other things to fix first, and clients are taking up all my time. That said, these repos are up to date with the latest Ember, you can check them out!

**Comment by alvinkatojr** [comment]
Thanks will do. And double thanks for the updated repos!
